# Generated by Django 5.0.6 on 2024-06-06 06:23

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawGameLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("season_year", models.CharField(max_length=10)),
                ("player_id", models.IntegerField()),
                ("player_name", models.CharField(max_length=50)),
                ("nickname", models.CharField(max_length=50)),
                ("team_id", models.IntegerField()),
                ("team_abbreviation", models.CharField(max_length=3)),
                ("team_name", models.CharField(max_length=50)),
                ("game_id", models.CharField(max_length=20)),
                ("game_date", models.CharField()),
                ("matchup", models.CharField(max_length=20)),
                ("wl", models.CharField(max_length=1)),
                ("min", models.FloatField()),
                ("fgm", models.IntegerField()),
                ("fga", models.IntegerField()),
                ("fg_pct", models.FloatField()),
                ("fg3m", models.IntegerField()),
                ("fg3a", models.IntegerField()),
                ("fg3_pct", models.FloatField()),
                ("ftm", models.IntegerField()),
                ("fta", models.IntegerField()),
                ("ft_pct", models.FloatField()),
                ("oreb", models.IntegerField()),
                ("dreb", models.IntegerField()),
                ("reb", models.IntegerField()),
                ("ast", models.IntegerField()),
                ("tov", models.IntegerField()),
                ("stl", models.IntegerField()),
                ("blk", models.IntegerField()),
                ("blka", models.IntegerField()),
                ("pf", models.IntegerField()),
                ("pfd", models.IntegerField()),
                ("pts", models.IntegerField()),
                ("plus_minus", models.IntegerField()),
                ("e_off_rating", models.FloatField()),
                ("off_rating", models.FloatField()),
                ("sp_work_off_rating", models.FloatField()),
                ("e_def_rating", models.FloatField()),
                ("def_rating", models.FloatField()),
                ("sp_work_def_rating", models.FloatField()),
                ("e_net_rating", models.FloatField()),
                ("net_rating", models.FloatField()),
                ("sp_work_net_rating", models.FloatField()),
                ("ast_pct", models.FloatField()),
                ("ast_to", models.FloatField()),
                ("ast_ratio", models.FloatField()),
                ("oreb_pct", models.FloatField()),
                ("dreb_pct", models.FloatField()),
                ("reb_pct", models.FloatField()),
                ("tm_tov_pct", models.FloatField()),
                ("e_tov_pct", models.FloatField()),
                ("efg_pct", models.FloatField()),
                ("ts_pct", models.FloatField()),
                ("usg_pct", models.FloatField()),
                ("e_usg_pct", models.FloatField()),
                ("e_pace", models.FloatField()),
                ("pace", models.FloatField()),
                ("pace_per40", models.FloatField()),
                ("sp_work_pace", models.FloatField()),
                ("pie", models.FloatField()),
                ("poss", models.FloatField()),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RawPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("person_id", models.IntegerField()),
                ("player_last_name", models.CharField(max_length=50)),
                ("player_first_name", models.CharField(max_length=50)),
                ("player_slug", models.CharField(max_length=50)),
                ("team_id", models.IntegerField()),
                ("team_slug", models.CharField(max_length=50, null=True)),
                ("is_defunct", models.IntegerField()),
                ("team_city", models.CharField(max_length=50)),
                ("team_name", models.CharField(max_length=50)),
                ("team_abbreviation", models.CharField(max_length=3)),
                ("jersey_number", models.CharField(max_length=10, null=True)),
                ("position", models.CharField(max_length=10, null=True)),
                ("height", models.CharField(max_length=10, null=True)),
                ("weight", models.CharField(max_length=10, null=True)),
                ("college", models.CharField(max_length=50, null=True)),
                ("country", models.CharField(max_length=50, null=True)),
                ("draft_year", models.IntegerField(null=True)),
                ("draft_round", models.IntegerField(null=True)),
                ("draft_number", models.IntegerField(null=True)),
                ("roster_status", models.IntegerField(null=True)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
