# Generated by Django 4.2.16 on 2024-10-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LeagueAverage9Cat",
        ),
    ]
