# Generated by Django 5.0.6 on 2024-06-11 04:25

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FantasyProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("season_year", models.CharField(max_length=10)),
                ("player_id", models.IntegerField()),
                ("min", models.FloatField()),
                ("pts", models.FloatField()),
                ("fg3m", models.FloatField()),
                ("reb", models.FloatField()),
                ("ast", models.FloatField()),
                ("stl", models.FloatField()),
                ("blk", models.FloatField()),
                ("fgm", models.FloatField()),
                ("fga", models.FloatField()),
                ("ftm", models.FloatField()),
                ("fta", models.FloatField()),
                ("tov", models.FloatField()),
                ("usg_pct", models.FloatField()),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
