# Generated by Django 4.2.16 on 2024-10-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="home_team",
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
