# Generated by Django 5.0.6 on 2024-07-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_remove_leagueaverage9cat_std_fg_pct_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawplayer",
            name="id",
        ),
        migrations.AlterField(
            model_name="rawplayer",
            name="person_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
