# Generated by Django 5.0.6 on 2024-07-31 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_remove_rawplayer_id_alter_rawplayer_person_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fantasyprojection",
            name="player_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.rawplayer"
            ),
        ),
        migrations.AlterField(
            model_name="projectionvalue",
            name="player_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.rawplayer"
            ),
        ),
        migrations.AlterField(
            model_name="rawgamelog",
            name="player_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.rawplayer"
            ),
        ),
    ]
