# Generated by Django 4.2.16 on 2024-10-23 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_fantasyteam_fantasyplayer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fantasyplayer",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_players",
                to="games.rawplayer",
            ),
        ),
    ]
