# Generated by Django 4.2.16 on 2024-10-23 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_alter_fantasyplayer_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fantasyplayer",
            name="fantasy_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_players",
                to="games.fantasyteam",
            ),
        ),
        migrations.AlterField(
            model_name="fantasyplayer",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.rawplayer"
            ),
        ),
    ]
