# Generated by Django 4.2.16 on 2024-10-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_alter_fantasyplayer_fantasy_team_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rawplayer",
            options={"ordering": ["player_first_name", "player_last_name"]},
        ),
        migrations.AddField(
            model_name="fantasyplayer",
            name="injured",
            field=models.BooleanField(default=False),
        ),
    ]
