# Generated by Django 4.2.16 on 2024-10-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_alter_rawplayer_options_fantasyplayer_injured"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fantasyteam",
            options={},
        ),
        migrations.AlterModelOptions(
            name="game",
            options={},
        ),
        migrations.AddIndex(
            model_name="fantasyteam",
            index=models.Index(
                fields=["team_name"], name="games_fanta_team_na_7b67a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["week_number"], name="games_game_week_nu_161b07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["home_team_id", "away_team_id"],
                name="games_game_home_te_c15004_idx",
            ),
        ),
    ]
