# Generated by Django 4.2.16 on 2024-10-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0010_weeklyteamgamecount"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weeklyteamgamecount",
            unique_together={("team_id", "week_number")},
        ),
    ]
