# Generated by Django 4.2.16 on 2024-10-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0011_alter_weeklyteamgamecount_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weeklyteamgamecount",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="weeklyteamgamecount",
            name="team_id",
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="weeklyteamgamecount",
            unique_together={("season_year", "team_id", "week_number")},
        ),
    ]
