# Generated by Django 4.2.16 on 2024-12-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0012_alter_weeklyteamgamecount_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_id",
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
